version: 2.1

commands:
  restore_dependencies:
    steps:
      - restore_cache:
          keys:
            - node-deps-v2-{{ .Branch }}-{{checksum "yarn.lock"}}

  save_dependencies:
    steps:
      - save_cache:
          key: node-deps-v2-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - node_modules

jobs:
  setup:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_dependencies
      - run:
          command: yarn install --frozen-lockfile
      - save_dependencies

  publish:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_dependencies
      - run:
          command: yarn build
      - run:
          command: yarn test
      - run:
          command: yarn shipit
      - run:
          name: NPM User
          command: npm --verbose whoami
          when: on_fail

workflows:
  build-test:
    jobs:
      - setup
      - publish:
          requires:
            - setup
          filters:
            branches:
              only: master
